#!/bin/bash -l

# Standard output and error:
##SBATCH -o ./sfincsJob.out.%j
##SBATCH -e ./sfincsJob.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J mgrid

# Queue (Partition):
#SBATCH --partition=express

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32

# Wall clock limit:
#SBATCH --time=00:30:00


srun /u/mlan/stellopt_github/develop/STELLOPT/bin/xvmec2000 input.2b40_freeBoundary
